modified:   PROJECT_INFO: added  version number new file:   dist/dpkg/debian: new directory as replacement for $PROJECT_NAME-$VER.debian deleted:    dist/dpkg/sh-make-tools_0.1-1.debian modified:   src/sh_make/sh_make.sh.in: $SH_MAKE_REV is now generated via $git_rev modified:   src/sh_make/sh_makefile: added handling to $git_rev modified:   src/shpp/shpp: fixed replace var handling modified:   tools/git_revgen

diff --git a/src/sh_make/sh_make.sh.in b/src/sh_make/sh_make.sh.in
--- a/src/sh_make/sh_make.sh.in
+++ b/src/sh_make/sh_make.sh.in
@@ -19,7 +19,7 @@
 
 ####################################
 SH_MAKE_VER=2.0
-SH_MAKE_REV=30
+SH_MAKE_REV=@git_rev@
 #####################################
 readonly SH_MAKE_REV SH_MAKE_VER
 #####################################
@@ -89,7 +89,7 @@ _ENV
 #
   export USE_COLOR
   # run used shell give it our main functions that we have, load the generated env file, load the main_module while inits module handling and such and than load the sh_makefile so that it can run with the given functions
-  "$used_shell"  -c$debug ". @prefix@/lib/sh_make/libsh_make; . @prefix@/lib/sh_make/modules/main_module; . $sh_makefile;. $PWD/$tmp_dir/env; test ! -z $temp_sh_makefile_dir &&  cd $temp_sh_makefile_dir; run_entry_point $entry_point" || call_handler error:exit "got error $? while running $sh_makefile"  
+  "$used_shell"  -c$debug ". @prefix@/lib/sh_make/libsh_make; . @prefix@/lib/sh_make/modules/main_module; test ! -z $temp_sh_makefile_dir &&  cd $temp_sh_makefile_dir; . $sh_makefile;. $PWD/$tmp_dir/env; run_entry_point $entry_point" || call_handler error:exit "got error $? while running $sh_makefile"  
 
 
   file_to_remove=$tmp_dir
@@ -141,9 +141,8 @@ case $1 in
     
     if [ ! -z "$sh_makefile" ]  ; then
       temp_sh_makefile_dir=$( dirname $sh_makefile )
-      if [  $temp_sh_makefile_dir = . ] ; then
-	 sh_makefile=$PWD/$sh_makefile
-      fi
+      sh_makefile=$PWD/$sh_makefile
+      
 
      # sh_makefile=${temp_sh_makefile_dir}$sh_makefile
      
