modified:   src/shpp/shpp: implemted to set macro and include space (-I, -M)

diff --git a/src/shpp/shpp b/src/shpp/shpp
--- a/src/shpp/shpp
+++ b/src/shpp/shpp
@@ -28,6 +28,8 @@ SHPP_REV=60
 defined_vars=all
 defined_all=true
 registed_commands=stub
+INCLUDE_SPACES=.
+MACRO_SPACES=.
 
 ################################################################
 
@@ -316,12 +318,28 @@ register_external() {
 
 #\\macro
 macro() {
-  verbose "found macro: $cleaned_macro, doing syntax check"
-  if sh -n $1 ; then
-      . $1
+  verbose "found macro: $1, doing syntax check"
+  case $1 in
+	\<*\>) 
+           __cleaned_macro=$(echo "$1" | sed -e 's/^<//' -e 's/>$//')
+	   for __macro_space in $MACRO_SPACES ; do
+	       if [ -e "$__macro_space"/"$__cleaned_macro" ] ; then
+		   __cleaned_macro="$__macro_space"/"$__cleaned_macro"
+	       else
+		   false
+	       fi
+	   done || \
+	   call_handler error:file "L$current_line_ued:$current_cleared_command: $__cleaned_include not found"
+	   ;;
+	   *) __cleaned_macro=$1;;
+    esac
+    
+  if sh -n $__cleaned_macro ; then
+      . $__cleaned_macro
   else
     call_handler error:syntax "$cleaned_macro don't passed syntax check, quiting"
   fi  
+  unset __cleaned_macro __macro_space
 }
 
 #### built im commands ###
@@ -423,31 +441,44 @@ include() {
     verbose "L$current_line_ued:Opened $1 to parse, call ourself to process file" 
     for __include_arg in $1 ; do
 	case $__include_arg in  
-	    noparse)  parser=no_parse ; call_handler warning:deprected 'no_parse is deprected now, use with care' ;;
-	    parser=*) parser=$( echo $1 | sed 's|parser=||' ) ;; # set parser to use another parser than shpp 
-	    parser_args=*) parser_args=$( echo $1 | sed 's|parser_args=||' ) ;; 
-	    *) cleaned_include="$__include_arg" ;;
+	    noparse)  __parser=no_parse ; call_handler warning:deprected 'no_parse is deprected now, use with care' ;;
+	    parser=*) __parser=$( echo $1 | sed 's|parser=||' ) ;; # set parser to use another parser than shpp 
+	    parser_args=*) __parser_args=$( echo $1 | sed 's|parser_args=||' ) ;; 
+	    *) __cleaned_include="$__include_arg" ;;
 	esac
     done
-    base_include=$( basename "$cleaned_include" )
-    case ${parser:-shpp} in 
-	shpp)  $shpp  $chained_options $parser_args --config $slaveconfig_file --defined-flags $defined_flags --enabled-flags $enabled_flags --tmp $tmp_dir/slaves --slave --stdout --stderr=$tmp_dir/logs/errors_$base_include.log "$cleaned_include"> $tmp_dir/including/$base_include  || call_handler error:exit_stat "spawned copy of ourself: $appname returned $?, quiting" ;; 
-	no_parse)  cp $cleaned_include $tmp_dir/including/$base_include ;; # no $parser is used
-	*) $parser $parser_args ;; # use $parser with $parser_args 
+    case $__cleaned_include in
+	\<*\>) 
+           __realy_cleaned_include=$(echo "$__cleaned_include" | sed -e 's/^<//' -e 's/>$//')
+	   for __include_space in $INCLUDE_SPACES ; do
+	       if [ -e "$__include_space"/"$__realy_cleaned_include" ] ; then
+		   __cleaned_include="$__include_space"/"$__realy_cleaned_include"
+	       else
+		   false
+	       fi
+	   done || \
+	   call_handler error:file "L$current_line_ued:$current_cleared_command: $__cleaned_include not found"
+	   ;;
+    esac
+    __outputfile__cleaned_include=$( echo $__cleaned_include | sed 's|\/|_|')
+    case ${__parser:-shpp} in  
+	shpp)  $shpp  $chained_options  --slave  $slaveconfig_file  --tmp $tmp_dir/slaves --stdout --stderr=$tmp_dir/logs/errors$__outputfile__cleaned_include.log "$__cleaned_include"> $tmp_dir/including/$__outputfile__cleaned_include  || call_handler error:exit_stat "spawned copy of ourself: $appname returned $?, quiting" ;; 
+	no_parse)  cp $__cleaned_include $tmp_dir/including/$__outputfile__cleaned_include ;; # no $parser is used
+	*) $__parser $__parser_args ;; # use $parser with $parser_args 
     esac
 
     if [ -z "$includes" ] ; then
-	includes="$base_include"
+	includes="$__outputfile__cleaned_include"
 	includes_lines="$current_line"
     else
-	includes="$includes:$base_include"
+	includes="$includes:$__outputfile__cleaned_include"
 	includes_lines="$includes_lines:$current_line"
     fi
 # for us and run argument of #\\include with us and copy to temp file/stdout
 # copy content before #\\include to new file
 # copy include argument to new file
 # copy content past #\\include to new file 
- unset __include_arg noparse parser parser_args cleaned_include base_include 
+ unset __include_arg  __parser __parser_args __cleaned_include __outputfile__cleaned_include  __realy_cleaned_include __include_space
 }
 
 #\\define
@@ -501,20 +532,33 @@ include_includes() {
     includes_lines=$( grep -hn \#\\\\\\\\include "$1"  | sed 's|:.*||' | tr '\n' ':')
     old_ifs=$IFS
     IFS='\n'
-    for _include in $( grep  \#\\\\\\\\include "$1" | sed -e 's/^#\\\\//' -e 's/^[ \t]*//' -e  's/^ //' ) ; do
+    for __include in $( grep  \#\\\\\\\\include "$1" | sed -e 's/^#\\\\//' -e 's/^[ \t]*//' -e  's/^ //' ) ; do
 	IFS=' '
-	for include_argument in $_include ; do
-	    case $include_argument in 
+	for __include_argument in $_include ; do
+	    case $__include_argument in 
 		include) : ;; 
 		noparse|parser=*|parser_args=*) : ;; # stub arguments that are only used by #\\include
-		*) _include=$include_argument ;;
+		*) __include=$include_argument ;;
 	    esac
 	done
+	case $__include in
+	    \<*\>) 
+                __realy_cleaned_include=$(echo "$__include" | sed -e 's/^<//' -e 's/>$//')
+		for __include_space in $INCLUDE_SPACES ; do
+		    if [ -e "$__include_space"/"$__realy_cleaned_include" ] ; then
+			__include="$__include_space"/"$__realy_cleaned_include"
+		    else
+			false
+		    fi
+		done 
+	   ;;
+	esac
+	__include=$( echo $__include | sed 's|\/|_|')
 	old_ifs=$IFS
-	_find_include_count=$(( $_find_include_count + 1 ))
+	__find_include_count=$(( $__find_include_count + 1 ))
 	current_include_line=$( read_farray $includes_lines  $_find_include_count )
-	tmp_include=$( read_farray $includes ${current_include_no:-1}  )
-	if [ $(basename $_include) = $tmp_include ] ; then
+	__tmp_include=$( read_farray $includes ${current_include_no:-1}  )
+	if [ $(basename $__include) = $__tmp_include ] ; then
 	    sed "$current_include_line,$ d" $1 > "$tmp_dir/including/cut_source"
 	    sed "1,$current_include_line d" $1 > "$tmp_dir/including/cut_source_end"
 	    cat "$tmp_dir/including/$tmp_include" >> "$tmp_dir/including/cut_source"
@@ -525,8 +569,8 @@ include_includes() {
 	fi
 	current_include_no=$(( ${current_include_no:-1}  + 1 ))
     done
-    unset include_lines _include include_argument _find_include_count \
-	current_include_line current_include_no    tmp_include
+    unset include_lines __include include_argument __find_include_count \
+	current_include_line current_include_no    __tmp_include __realy_cleaned_include __include_space
 }
 
 replace_vars() {
@@ -650,8 +694,8 @@ if [ ! $# = 0 ] ; then
 	    -V|--version)	echo $SHPP_VER:$SHPP_REV  ; shift ;;
             #   #-*)		echo `read_farray "$err_input_messages" 1`;;
 	    --*|*)
-		optspec=o:O:C:cD: # b:dp #-: # short options
-		optspec_long=defined-flags:,defined-vars:,enabled-flags:,output:,option:,Ow:,option-global:,config:,color,pass-all-to-slaves,legacy,stdout,critical-warning,tmp:,stderr:,keep,slave,debug,errexit,\*=\* #,binpath:,desktop,prefix # long options
+		optspec=o:O:C:cD:I:M: # b:dp #-: # short options
+		optspec_long=output:,option:,Ow:,option-global:,config:,color,pass-all-to-slaves,legacy,stdout,critical-warning,tmp:,stderr:,keep,slave:,debug,errexit,\*=\* #,binpath:,desktop,prefix # long options
 		PROCESSED_OPTSPEC=$( getopt -qo $optspec --long $optspec_long \
 		    -n $appname -- "$@" ) || error_msg input "Wrong or to less  input given!" ||  exit 1 
 		eval set -- "$PROCESSED_OPTSPEC"; 
@@ -665,7 +709,7 @@ if [ ! $# = 0 ] ; then
 			    ;;
 			--errexit) set -o errexit ; shift ;;
 			-c|--color) USE_COLOR=true ; shift 1 ;;
-			-C|--config) . "$2" ; slaveconfig_file="$2" ;shift 2;;
+			-C|--config) . "$2"  ;shift 2;;
 			-O|--option) # pass options to shpp or enable options
 			    case $2 in 
 				*=*) eval $2 ; pass_chain -g $2 ;; # self explained
@@ -685,7 +729,7 @@ if [ ! $# = 0 ] ; then
 			--tmp) tmp_dir=${2} ; shift 2;;
 			--keep) keep=true; shift ;; # keep temp files
 			--critical-warning) WARNING_IS_ERROR=true ; shift ;; # all warnings are critical
-			--slave) slave=true; shift ;; # process is a slave, it now links to their master and dont provides links to its directorys in main temp
+			--slave) slaveconfig_file="$2"; . $slaveconfig_file; slave=true; shift ;; # process is a slave, it now links to their master and dont provides links to its directorys in main temp
 # 
 			--defined-flags|--defined-vars)  input_defined_vars=${2} ; shift 2 ;;
 			-D)
@@ -695,6 +739,8 @@ if [ ! $# = 0 ] ; then
 			    unset arg0 arg1
 			    shift 2
 			    ;;
+			-I) INCLUDE_SPACES=$2:$INCLUDE_SPACES; shift 2;;
+			-M) MACRO_SPACES=$2:$MACRO_SPACES; shift 2;;
 			-o|--output) target_name="$2"; shift 2 ;;
 			--pass-all-to-slaves) give_them_all=true; shift ;; # pass all option to slaves
 			--legacy) legacy_mode=true ; shift ;;
