modified:   doc/sh_makefile 		added option to compress man pages with gzip 	modified:   doc/shpp.1 		restored original file cause its easyer to edit non-compressed files
	modified:   src/sh_make/sh_make.sh.in
		fixed some stuff
	modified:   src/shpp/shpp
		Fixed some stuff and added functionality to give option via -O and to pass options to slaves or too both (use with care)
		34-39:
			fixed self detection (for shpp():)
		pass_chain():
			pass given chains to slaves or master
			init commit
		pass_chaines():
			pass chaines to $tmp_dir and pass all options to slaves if $give_them_all is set
			init_commit
		include():
			fixed stderr parameter

		print_help():
			updated info text

		# input ###:
			-o --output: added long option
			-O --option: added option to give shpp options manually (without --*)
			-C --config:added option to give slaves options
			--pass-all-to-slaves: added option to give slave all options of master (not all but the most, exept parameters like --slave)

diff --git a/src/shpp/shpp b/src/shpp/shpp
--- a/src/shpp/shpp
+++ b/src/shpp/shpp
@@ -19,8 +19,8 @@
 # config vars ### 
 ####################################
 # version, rev config
-SHPP_VER=0.1
-SHPP_REV=30
+SHPP_VER=0.5
+SHPP_REV=60
 #####################################
 # base config 
 
@@ -31,12 +31,11 @@ SHPP_REV=30
 ################################################################
 
 . "${libdir:-/usr/lib}/libsh"
-if [  "$0" = */* ] ; then
-  shpp=$0
+if [ $( dirname $0 ) = . ] ; then
+   shpp=$(which shpp) || shpp=$( dirname $0 )/shpp
 else
-  shpp=$(which shpp) || shpp=$0 
+  shpp=$( dirname $0 )/shpp
 fi
-
 
 
 stub() {
@@ -120,7 +119,7 @@ verbose() {
 call_handler() {
   case $1 in
     error*) error "$@"; die=1 ;;
-    warning*) test ! -z  $WARNING_IS_ERROR = true && die=1; warning "$@";; 
+    warning*) test "$WARNING_IS_ERROR" = true && die=1; warning "$@";; 
   esac
   if [ $die ]  ; then
     verbose 'got signal to die, dieing'
@@ -158,6 +157,26 @@ cleanup_die() {
  
   export IFS=$old_ifs
 
+}
+
+pass_chain() {
+  case $1 in 
+    -g|--global)	echo "$2">>"${tmp_dir:-$PWD}/master_config" ;;
+    *)			echo "$1">>"${tmp_dir:-$PWD}/slaveconfig" ;;
+  esac
+  
+}
+parse_chaines() {
+  mv -f slaveconfig	"$tmp_dir/slaveconfig" > /dev/null 2>&1  || echo "destination=valhalla" > "$tmp_dir/slaveconfig"
+  mv -f master_config	"$tmp_dir/master_config" > /dev/null 2>&1  
+
+  if [ "$give_them_all" = true ] ; then
+    cat $tmp_dir/slaveconfig >> $tmp_dir/master_config 
+
+    [ $WARNING_IS_ERROR = true ] && pass_chain -g WARNING_IS_ERROR=true 
+    [ $keep ] && pass_chain -g keep=true
+  fi
+  
 }
 
 
@@ -285,7 +304,7 @@ include() {
   base_include=$( basename "$cleaned_include" )
  # echo "$base_include"
   if [ ! $noparse ] ; then 
-    shpp --defined-flags $defined_flags --enabled-flags $enabled_flags --tmp $tmp_dir/slaves --slave --stdout --stder $tmp_dir/log/errors_$base_include.log "$cleaned_include"> $tmp_dir/including/$base_include  || call_handler error:exit_stat "spawned copy of ourself: $appname returned $$, quiting"
+    shpp  $chained_options --config $tmp_dir/slaveconfig --defined-flags $defined_flags --enabled-flags $enabled_flags --tmp $tmp_dir/slaves --slave --stdout --stderr $tmp_dir/log/errors_$base_include.log "$cleaned_include"> $tmp_dir/including/$base_include  || call_handler error:exit_stat "spawned copy of ourself: $appname returned $$, quiting"
   else
     cp $cleaned_include $tmp_dir/including/$base_include
   fi
@@ -380,10 +399,12 @@ main() {
       fi
   fi
   tmp_dir=$tmp_dir/$$
+
   mkdir -p "$tmp_dir/including"
   mkdir -p "$tmp_dir/backups"
   mkdir -p "$tmp_dir/logs"
   mkdir -p "$tmp_dir/slaves"
+  parse_chaines
   if [ $slave ] ; then
     ln -s "../.."	"$tmp_dir/master"
     files_to_remove=$tmp_dir
@@ -440,12 +461,15 @@ $appname usage:
     --help -H		print this help
     --version		print version
 		
-   -o <file>		places output in file
-  --stdout		all output goes to stdout
-  --critical-warning    warnings are threated as errors
-  --tmp=                set temp directory
-  --keep 		don't delete tmp files after running
-  --stderr=file   	stderr goes to file
+  -o --output		<file>		places output in file
+  -O --option		<option>	give $appname <option>
+  --Ow --option-global	<option>  
+  --pass-all-to-slaves			pass all options to slaves
+  --stdout				all output goes to stdout
+  --critical-warning    		warnings are threated as errors
+  --tmp=                		set temp directory
+  --keep 				don't delete tmp files after running
+  --stderr=file   			stderr goes to file
 
   --defined-flags       give $appname flags to define that are not defined in file, seperated with :.
   --enabled-flags       give $appname flags to enable, same seperator :
@@ -465,8 +489,8 @@ if [ ! $# = 0 ] ; then
       -V|--version)	echo $SHPP_VER:$SHPP_REV  ; shift ;;
     #   #-*)		echo `read_farray "$err_input_messages" 1`;;
       --*|*)
-	      optspec=o: # b:dp #-: # short options
-    optspec_long=defined_flags:,enabled_flags:,legacy,stdout,critical-warning,tmp:,stder:,keep,slave,\*=\* #,binpath:,desktop,prefix # long options
+    optspec=o:O:C: # b:dp #-: # short options
+    optspec_long=defined_flags:,enabled_flags:,output:,option:,Ow:,option-global:,config:,pass-all-to-slaves,legacy,stdout,critical-warning,tmp:,stderr:,keep,slave,\*=\* #,binpath:,desktop,prefix # long options
     PROCESSED_OPTSPEC=`getopt -qo $optspec --long $optspec_long \
     -n $appname -- "$@"` 
     eval set -- "$PROCESSED_OPTSPEC"
@@ -474,13 +498,30 @@ if [ ! $# = 0 ] ; then
 	    case $1 in 
 	      --defined-flags)  input_defined_flags=${2} ; shift 2 ;;
 	      --enabled-flags)  input_enabled_flagst=${2} ; shift  2;;
-	      -o) target_name="$2"; shift 2 ;;
+	      -o|--output) target_name="$2"; shift 2 ;;
+	      -O|--option) # pass options to shpp or enable options
+		case $2 in 
+		  *=*) eval $2 ; pass_chain -g $2 ;; # self explained
+		  *) $2=true ; pass_chain -g $2=true ;;  # if its no var (options can be paased as var too) threat it as option and enable it
+		esac
+		shift 2 
+		;;
+	      #+O) $1=false ; shift 2;; # tell shppp to disable option
+	      --Ow|--option-global) 					# pass option to slave and master
+		case $2 in 
+		  *=*) eval $2 ; pass_chain $2 ;; # self explained
+		  *) $2=true ; pass_chain $2=true ;;  # if its no var (options can be paased as var too) threat it as option and enable it
+		esac
+		shift 2 
+		;;
+	      -C|--config) . "$2" ; shift 2;;
+	      --pass-all-to-slaves) give_them_all=true; shift ;; # pass all option to slaves
 	      --legacy) legacy_mode=true ; shift ;;
 	      --stdout) target_name="stdout" ; shift ;;
-	      --critical-warning) WARNING_IS_ERROR=true ; shift ;;
+	      --critical-warning) WARNING_IS_ERROR=true ; shift ;; # all warnings are critical
 	      --tmp) tmp_dir=${2} ; shift 2;;
-	      --stderr) stder=${2} ; shift  2;;
-	      --keep) keep=true; shift ;;
+	      --stderr) stder=${2} ; shift  2;; # tells shpp to pass stder to $2
+	      --keep) keep=true; shift ;; # keep temp files
 	      --slave) slave=true; shift ;; # process is a slave, it now links to their master and dont provides links to its directorys in main temp
 	      --) shift; break ;;
 	    esac
