modified:   src/shpp/shpp: now using /dev/stdout as default output  if  -o or  --stdout was not given and displaing warning init_stats(): we check now if output is piped and disable colored output if FORCE_COLOR is not set

diff --git a/src/shpp/shpp b/src/shpp/shpp
--- a/src/shpp/shpp
+++ b/src/shpp/shpp
@@ -45,7 +45,8 @@ stub() {
 
 
 init_stats(){
-    if [ $USE_COLOR ] ; then # use only colored out if enabled and if output goes to the terminal
+  if [  -t 1 ] || ( [ $FORCE_COLOR ] && [ ! $FORCE_COLOR = n ] ) ; then
+    if  [ $USE_COLOR ] && [ ! $USE_COLOR = [Nn] ] || ( [ $FORCE_COLOR ] && [ ! $FORCE_COLOR = n ]  ) ; then # use only colored out if enabled and if output goes to the terminal
 	# prefer terminal safe colored and bold text when tput is supported [ ! -t 1 ]  && 
 	if tput setaf 0 > /dev/null 2>&1 ; then
 		ALL_OFF="$(tput sgr0)"
@@ -63,7 +64,7 @@ init_stats(){
 		YELLOW="${BOLD}\e[1;33m"
 	fi
     fi
-
+ fi
 }
 # 
 
@@ -576,11 +577,12 @@ if [ ! $# = 0 ] ; then
 	    esac
 	  done
 	  if [ -z "$target_name" ] ; then
-	      target_name="$1"
+	      target_name=stdout
+	      warning_msg warning "using /dev/stdout as default output"
 	  fi && \
 	  source_file="$1" && \
 	  if [ ! -e "$source_file" ] ; then
-	    echo "$source_file not found" 
+	    error_msg error  "$source_file not found" 
 	    false
 	    shift
 	  fi && \
