modified:   src/shpp/sh_makefile: fixed tests() target modified:   src/shpp/shmk_local/do_tests: fixed tests macro modified:   src/shpp/shpp: some cleanup in option parser, added --debug option (set -o verbose xtrace), added option --errexit (set -o errexit)

diff --git a/src/shpp/shmk_local/do_tests b/src/shpp/shmk_local/do_tests
--- a/src/shpp/shmk_local/do_tests
+++ b/src/shpp/shmk_local/do_tests
@@ -1,10 +1,14 @@
 #!/bin/sh
-do_test() {
+do_tests() {
 	testrun=$1
 	shift
-  for test_file in TESTFILES ; do
+	IFS=" "
+  for test_file in $TESTFILES ; do
 		__testrun=$(echo "$testrun" | sed "s|%f|$test_file|")
-		eval $test_file > $test_file.fine || ( error error:return_stat "${testrun%\ *} returned $? on $testfile, saving result to $test_file.ftest"; \
-												mv $test_file.fine $test_file.fail
+		eval $__testrun > $test_file.fine
+		if [ $? -ge 1 ]   ; then 
+			error error:return_stat "${testrun%\ *} returned $? on $testfile, saving result to $test_file.fail" 
+			mv $test_file.fine $test_file.fail
+		fi
 	done
 }
