modified:   src/shpp/sh_makefile: tests() added --errexit as option to shpp modified:   src/shpp/shmk_local/do_tests: fixed error status reporing modified:   src/shpp/shpp: parse_chaines(): ignore return status from mv

diff --git a/src/shpp/shmk_local/do_tests b/src/shpp/shmk_local/do_tests
--- a/src/shpp/shmk_local/do_tests
+++ b/src/shpp/shmk_local/do_tests
@@ -6,8 +6,9 @@ do_tests() {
   for test_file in $TESTFILES ; do
 		__testrun=$(echo "$testrun" | sed "s|%f|$test_file|")
 		eval $__testrun > $test_file.fine
-		if [ $? -ge 1 ]   ; then 
-			error error:return_stat "${testrun%\ *} returned $? on $testfile, saving result to $test_file.fail" 
+		saved_return_status=$?
+		if [ $saved_return_status -ge 1 ]   ; then 
+			error error:return_status "${testrun%\ *} returned $saved_return_status  on $testfile, saving result to $test_file.fail" 
 			mv $test_file.fine $test_file.fail
 		fi
 	done
diff --git a/src/shpp/shpp b/src/shpp/shpp
--- a/src/shpp/shpp
+++ b/src/shpp/shpp
@@ -167,8 +167,8 @@ pass_chain() {
   
 }
 parse_chaines() {
-  mv -f slaveconfig	"$tmp_dir/slaveconfig" > /dev/null 2>&1  || echo "destination=valhalla" > "$tmp_dir/slaveconfig"
-  mv -f master_config	"$tmp_dir/master_config" > /dev/null 2>&1  
+  mv -f slaveconfig	"$tmp_dir/slaveconfig" > /dev/null 2>&1  || echo "destination=valhalla" > "$tmp_dir/slaveconfig" || true # ignore this error it isn't needed
+  mv -f master_config	"$tmp_dir/master_config" > /dev/null 2>&1  || true 
 
   if [ "$give_them_all" = true ] ; then
     cat $tmp_dir/slaveconfig >> $tmp_dir/master_config 
